/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <YouTube/YouTube.h>
#import <UIKit/UIKit.h>

@class YTSelectPlaylistView, YTVideoInfoTableViewCell, YTLoadTableViewCell;

@interface YTVideoRelatedView : UITableView <UITableViewDelegate, UITableViewDataSource> {
	YTVideo *_video;
	BOOL _videoIsBookmarked;
	YTVideoInfoTableViewCell *_infoCell;
	YTLoadTableViewCell *_loadingRelatedCell;
	UIButton *_bookmarkButton;
	UIButton *_addToPlaylistButton;
	UIButton *_shareButton;
	NSArray *_relatedVideos;
	YTSearchRequest *_relatedVideosRequest;
	YTSelectPlaylistView *_selectPlaylistView;
	BOOL _hasPlaylistChangedObserver;
	UIView *_firstSectionFooter;
}
@property(retain) YTVideo *video;
+ (UIFont *)_buttonFont;
+ (UIColor *)_buttonLabelColor;
+ (UIFont *)_smallButtonFont;
- (id)initWithFrame:(CGRect)frame video:(YTVideo *)video;
- (void)_addBookmark;
- (void)_addToPlaylist;
- (void)_createUIIfNecessary;
- (void)_destroyUI;
- (void)_loadThumbnailsAfterScroll;
- (void)_setRelatedVideos:(id)videos;
- (void)_shareVideo;
- (void)_shareVideo:(id)video;
- (void)dealloc;
- (void)movedFromSuperview:(id)superview;
- (void)movedToSuperview:(id)superview;
- (int)numberOfSectionsInTableView:(id)tableView;
- (void)scrollViewDidEndDecelerating:(id)scrollView;
- (void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
- (void)searchRequest:(id)request didFailWithError:(id)error;
- (void)searchRequest:(id)request receivedVideos:(id)videos startIndex:(unsigned)index videosRemaining:(unsigned)remaining;
- (void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
- (UITableViewCell *)tableView:(UITableView *)view cellForRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)view didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
- (float)tableView:(UITableView *)view heightForFooterInSection:(int)section;
- (float)tableView:(UITableView *)view heightForHeaderInSection:(int)section;
- (float)tableView:(UITableView *)view heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (int)tableView:(UITableView *)view numberOfRowsInSection:(int)section;
- (UIView *)tableView:(UITableView *)view viewForFooterInSection:(int)section;
- (UIView *)tableView:(UITableView *)view viewForHeaderInSection:(int)section;
- (void)willHide;
- (void)willShow;
@end

@interface YTVideoRelatedView (Internal)
- (void)YTSelectPlaylistView:(id)view didSelect:(id)select;
- (void)YTSelectPlaylistViewDidCancel:(id)ytselectPlaylistView;
- (void)_addPlaylistChangedObserver;
- (void)_cancelRelatedVideosRequest;
- (UIView *)_contentView;
- (void)_findRelatedVideos;
- (void)_hideSelectPlaylistAnimationDidStop;
- (void)_hideSelectPlaylistView;
- (BOOL)_isLoadingRelatedVideos;
- (void)_playlistsDidChange;
- (void)_removePlaylistChangedObserver;
- (UIView *)_selectPlaylistView;
- (void)_showSelectPlaylistView;
- (void)_updateBookmarkButton;
- (void)_updatePlaylistButton;
@end
