/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YouTube-Structs.h"
#import <Foundation/Foundation.h>

@interface XMLSAXHTTPRequest : NSObject {
	NSURLRequest *_request;
	NSURLConnection *_connection;
	NSMutableData *_rawData;
	xmlSAXHandler _saxHandler;
	BOOL _invalidResponse;
}
@property(readonly, retain) NSURLRequest *request;	// converted property
+ (BOOL)anyRequestLoading;
+ (NSError *)serviceUnavailableError;
+ (unsigned)uniqueQueryID;
- (id)init;
- (void)_finishedLoading;
- (void)_startedLoading;
- (void)cancel;
- (void)connection:(NSURLConnection *)connection didFailWithError:(NSError *)error;
- (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data;
- (void)connection:(NSURLConnection *)connection didReceiveResponse:(NSURLResponse *)response;
- (void)connectionDidFinishLoading:(NSURLConnection *)connection;
- (void)dealloc;
- (void)didParseData;
- (void)failWithError:(NSError *)error;
- (BOOL)isLoading;
- (void)loadRequest:(NSURLRequest *)request;
- (void)loadStatusChanged;
- (int)parseData:(NSData *)data;
- (BOOL)receivedValidResponse:(NSURLResponse *)response;
// converted property getter: - (id)request;
- (void)willParseData;
@end

