/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <pthread.h>
#import <CoreFoundation/CoreFoundation.h>
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "YouTube-Structs.h"
#import "YTNetworkController.h"
#import "YTWebServiceConfig.h"
#import "YTAuthenticatorDeferredRequest.h"
#import "YTAuthenticator.h"
#import "YTBookmarksVideoDataSource.h"
#import "YTVideo.h"
#import "YTSearchRequest.h"
#import "YTHistoryVideoDataSource.h"
#import "YTFeaturedVideoDataSource.h"
#import "YTTopRatedVideoDataSource.h"
#import "YTCategoriesRequest.h"
#import "YTAccountAuthenticator.h"
#import "YTPersistentVideoList.h"
#import "YTSearchVideoDataSource.h"
#import "YTVideoDataSource.h"
#import "YTImageLoad.h"
#import "YTRecentlyAddedVideoDataSource.h"
#import "YTFavoritesController.h"
#import "YTTestVideoDataSource.h"
#import "YTCommentsRequest.h"
#import "YTImageLoader.h"
#import "YTMovieView.h"
#import "XMLSAXHTTPRequest.h"
#import "YTVideoReference.h"
#import "YTDeviceAuthenticator.h"
#import "YTTimeQualifiedVideoDataSource.h"
#import "YTRelatedVideoDataSource.h"
#import "YTSubscriptionsVideoDataSource.h"
#import "YTAuthenticatedAccountPost.h"
#import "YTFeedRequest.h"
#import "YTMostViewedVideoDataSource.h"
#import "YTSubscriptionsRequest.h"
#import "YTAccountFeedRequest.h"
#import "YTMoreByAuthorVideoDataSource.h"
#import "YTMyVideosVideoDataSource.h"
