/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YouTube-Structs.h"
#import "YTFeedRequest.h"


@interface YTAccountFeedRequest : YTFeedRequest {
}
- (void)addVideo:(id)video toPlaylist:(id)playlist;
- (void)addVideosToFavorites:(id)favorites withBatchURL:(id)batchURL;
- (void)didParseData;
- (void)failWithError:(id)error;
@end

