/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>

@interface YTAccountAuthenticator : NSObject {
	NSString *_accountToken;
	NSDate *_accountTokenDate;
	NSString *_account;
	NSString *_accountYouTubeName;
	NSString *_password;
	NSMutableData *_responseData;
	NSHTTPURLResponse *_urlResponse;
	NSString *_authURLBase;
}
@property(readonly, retain) NSString *accountYouTubeName;	// converted property
+ (id)sharedAuthenticator;
- (id)init;
- (id)_authRequestForAccount:(id)account password:(id)password;
- (id)_authRequestWithURL:(id)url;
- (void)_clearURLResponseInfo;
- (void)_getNewTokenForAccount:(id)account password:(id)password;
- (BOOL)_isTokenExpired:(id)expired;
- (id)_passwordFromKeychain;
- (void)_postAccountTokenGenerationFailedWithError:(id)error;
- (void)_postNewAccountTokenAvailable;
- (void)_removePasswordFromKeychain;
- (void)_setAccount:(id)account;
- (void)_setAccountToken:(id)token;
- (void)_setAccountTokenDate:(id)date;
- (void)_setAccountYouTubeName:(id)name;
- (void)_setPassword:(id)password;
- (void)_setURLResponse:(id)response;
// converted property getter: - (id)accountYouTubeName;
- (BOOL)cachedCredentialsValid;
- (void)clearAccountInfo;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connectionDidFinishLoading:(id)connection;
- (void)dealloc;
- (BOOL)readyToRequestToken;
- (id)tokenForCurrentAccount;
- (void)validateAccount:(id)account password:(id)password;
@end

