/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>
#import "YouTube-Structs.h"
#import "XMLSAXHTTPRequest.h"

@interface YTCategoriesRequest : XMLSAXHTTPRequest {
	id _delegate;
	NSMutableArray *_categories;
	NSMutableURLRequest *_deferredRequest;
}
- (id)init;
- (id)_categoriesURL;
- (void)_didAuthenticate:(id)authenticate;
- (void)_failedToAuthenticate:(id)authenticate;
- (void)_listenForAuthenticationNotifications:(BOOL)authenticationNotifications;
- (void)clearDelegate;
- (void)dealloc;
- (void)didParseData;
- (void)failWithError:(id)error;
- (void)loadRequest:(id)request;
- (int)parseData:(id)data;
- (void)requestCategoriesWithDelegate:(id)delegate;
@end

