/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>
#import "XMLSAXHTTPRequest.h"
#import "YTVideo.h"

@interface YTCommentsRequest : XMLSAXHTTPRequest {
	id _delegate;
	BOOL _isLoading;
	NSMutableArray *_comments;
	unsigned _startIndex;
	unsigned _totalResults;
	NSMutableURLRequest *_deferredRequest;
	NSMutableString *_moreCommentsURLString;
	YTVideo *_video;
}
@property(readonly, assign) BOOL isLoading;	// converted property
+ (unsigned)commentsPerRequest;
- (id)initRequestingCommentsForVideo:(id)video withDelegate:(id)delegate;
- (void)_didAuthenticate:(id)authenticate;
- (void)_failedToAuthenticate:(id)authenticate;
- (void)_listenForAuthenticationNotifications:(BOOL)authenticationNotifications;
- (void)_requestCommentsFromURL:(id)url;
- (void)dealloc;
- (void)didParseData;
- (void)failWithError:(id)error;
// converted property getter: - (BOOL)isLoading;
- (void)loadRequest:(id)request;
- (int)parseData:(id)data;
- (void)requestMoreComments;
@end

