/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YouTube-Structs.h"
#import <Foundation/Foundation.h>

@interface YTDeviceAuthenticator : NSObject {
	NSURLConnection *_connection;
	NSMutableData *_responseData;
	NSString *_token;
	double _timeTokenGranted;
	int _phase;
	NSData *_r1;
	NSData *_r1Hash;
	NSData *_r2;
	NSData *_hmac;
}
@property(readonly, retain) NSString *token;	// converted property
+ (id)sharedAuthenticator;
- (BOOL)_authenticate1;
- (BOOL)_authenticate2;
- (void)_clearNonces;
- (void)_connectionDidEnd;
- (void)_copyCertificateData:(id *)data privateKey:(SecKey **)key;
- (void)_failWithErrorCode:(int)errorCode;
- (void)_loadStatusChanged;
- (void)_succeeded;
- (void)authenticate;
- (BOOL)canAuthenticate;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connectionDidFinishLoading:(id)connection;
- (void)invalidateToken;
- (BOOL)isAuthenticating;
// converted property getter: - (id)token;
@end

