/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>

@class YTAuthenticatedAccountPost;
@class YTAccountFeedRequest;
@protocol YTFavoritesControllerDelegate;

@interface YTFavoritesController : NSObject {
	NSMutableArray *_pendingFavoritesShortIDs;
	NSMutableArray *_mergedFavorites;
	YTAuthenticatedAccountPost *_accountPost;
	YTAccountFeedRequest *_accountFeedRequest;
	BOOL _usingAccountFavorites;
	BOOL _shouldOfferMergeOfLocalBookmarks;
	NSURL *_batchURL;
	NSMutableArray *_bookmarkVideos;
	NSMutableArray *_bookmarkShortIDs;
	id<YTFavoritesControllerDelegate> _mergeBookmarksDelegate;
}
@property(retain) NSURL *batchURL;	// converted property
@property(readonly, assign) BOOL shouldOfferMergeOfLocalBookmarks;	// converted property
@property(assign) BOOL usingAccountFavorites;	// converted property
+ (id)sharedFavoritesController;
- (void)YTAuthenticatedAccountPost:(id)post didFinishWithType:(int)type error:(id)error;
- (void)_bookmarksDidChangeNotifyObservers:(BOOL)_bookmarks;
- (void)_loadBookmarks;
- (void)_processNextPendingFavoritesBatch;
- (void)_saveBookmarks;
- (void)accountFeedRequest:(id)request didFailWithError:(id)error;
- (void)accountFeedRequest:(id)request receivedVideos:(id)videos;
- (void)addFavoriteForVideo:(id)video;
- (void)addLocalBookmarkForVideo:(id)video;
// converted property getter: - (id)batchURL;
- (id)bookmarkedShortIDs;
- (id)bookmarkedVideos;
- (void)bookmarksSearchRequestInterrupted;
- (void)dealloc;
- (void)mergeLocalBookmarksToAccountFavoritesWithDelegate:(id)delegate;
- (void)removeFavoriteForVideo:(id)video;
- (void)saveBookmarksIfNeeded;
- (void)searchRequestReturnedVideos:(id)videos;
// converted property setter: - (void)setBatchURL:(id)url;
- (void)setLocalBookmarksMergeOffered;
// converted property setter: - (void)setUsingAccountFavorites:(BOOL)favorites;
// converted property getter: - (BOOL)shouldOfferMergeOfLocalBookmarks;
// converted property getter: - (BOOL)usingAccountFavorites;
@end

