/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>
#import "YouTube-Structs.h"
#import "XMLSAXHTTPRequest.h"

@interface YTFeedRequest : XMLSAXHTTPRequest {
	id _delegate;
	NSMutableArray *_videos;
	NSURL *_batchURL;
	unsigned _startIndex;
	unsigned _videosPerPage;
	unsigned _totalResults;
	BOOL _invalidatedToken;
	BOOL _isLoading;
	BOOL _accountAuthRequired;
	NSMutableURLRequest *_deferredRequest;
}
@property(readonly, assign) BOOL isLoading;	// converted property
- (id)init;
- (void)_didAuthenticate:(id)authenticate;
- (void)_failedToAuthenticate:(id)authenticate;
- (void)dealloc;
- (void)didParseData;
- (void)failWithError:(id)error;
// converted property getter: - (BOOL)isLoading;
- (void)listenForAuthenticationNotifications:(BOOL)authenticationNotifications;
- (void)loadRequest:(id)request;
- (void)loadRequest:(id)request withDelegate:(id)delegate accountAuthRequired:(BOOL)required;
- (int)parseData:(id)data;
- (void)setDelegate:(id)delegate;
@end

