/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>

@interface YTImageLoad : NSObject {
	NSURL *_URL;
	NSURLConnection *_connection;
	NSMutableData *_imageData;
	NSString *_videoID;
}
- (void)_createImage;
- (void)_loadFinished;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connectionDidFinishLoading:(id)connection;
- (void)dealloc;
- (void)start;
@end

