/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YouTube-Structs.h"
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "YTVideo.h"

@class YTSearchRequest;
@class UIMoviePlayerController;
@interface YTMovieView : UIView {
	id _delegate;
	YTVideo *_video;
	NSArray *_videoList;
	NSURL *_youTubeURL;
	YTSearchRequest *_videoInfoRequest;
	UIMoviePlayerController *_moviePlayer;
	UIImageView *_bugView;
	UIImageView *_gradientView;
	BOOL _canAutoPlay;
	BOOL _shownFromExternalURL;
	BOOL _switchingVideos;
	BOOL _controlsShown;
	BOOL _useSmallLogo;
	double _seekTime;
}
@property(readonly, retain) UIMoviePlayerController *moviePlayer;	// converted property
@property(readonly, retain) YTVideo *video;	// converted property
- (id)initWithFrame:(CGRect)frame;
- (BOOL)_canBookmark;
- (BOOL)_canShare;
- (void)_cancelVideoInfoRequest;
- (void)_destroyMoviePlayer;
- (void)_hideBug;
- (void)_hideOverlay;
- (void)_loadVideoFromURL:(BOOL)url;
- (void)_loadVideoInfoWithID:(id)anId;
- (void)_presentAlertForError:(id)error;
- (void)_setupBackground;
- (void)_switchToVideo:(id)video;
- (BOOL)canContinuePlayingWhenLocked;
- (void)dealloc;
- (void)didHide;
- (void)didShow;
- (void)forceControlsVisible:(BOOL)visible;
- (UIView *)fullscreenView;
- (BOOL)isPlaying;
// converted property getter: - (id)moviePlayer;
- (BOOL)moviePlayer:(id)player validateAction:(SEL)action;
- (BOOL)moviePlayerAddBookmarkButtonPressed:(id)pressed;
- (BOOL)moviePlayerBackwardButtonPressed:(id)pressed;
- (void)moviePlayerBufferingStateDidChange:(id)moviePlayerBufferingState;
- (void)moviePlayerDidExitFullscreen:(id)moviePlayer;
- (void)moviePlayerDidHideOverlay:(id)moviePlayer;
- (void)moviePlayerDidShowOverlay:(id)moviePlayer;
- (BOOL)moviePlayerEmailButtonPressed:(id)pressed;
- (BOOL)moviePlayerExitRequest:(id)request exitReason:(int)reason;
- (BOOL)moviePlayerForwardButtonPressed:(id)pressed;
- (CGRect)moviePlayerFrameAfterFullscreenExit:(id)exit;
- (BOOL)moviePlayerHeadsetNextTrackPressed:(id)pressed;
- (BOOL)moviePlayerHeadsetPreviousTrackPressed:(id)pressed;
- (void)moviePlayerPlaybackDidEnd:(id)moviePlayerPlayback;
- (void)moviePlayerPlaybackStateDidChange:(id)moviePlayerPlaybackState fromPlaybackState:(unsigned)playbackState;
- (void)moviePlayerWillEnterFullscreen:(id)moviePlayer;
- (void)moviePlayerWillExitFullscreen:(id)moviePlayer;
- (void)moviePlayerWillHideOverlay:(id)moviePlayer;
- (void)moviePlayerWillShowOverlay:(id)moviePlayer;
- (int)orientation;
- (void)pause;
- (void)play;
- (void)searchRequest:(id)request didFailWithError:(id)error;
- (void)searchRequest:(id)request receivedVideos:(id)videos startIndex:(unsigned)index videosRemaining:(unsigned)remaining;
- (void)setCanAutoPlay:(BOOL)play;
- (void)setDelegate:(id)delegate;
- (void)setFrame:(CGRect)frame;
- (void)setFullscreen:(BOOL)fullscreen;
- (void)setSeekTime:(double)time;
- (void)shareSheetDidHide;
- (void)useSmallLogo:(BOOL)logo;
// converted property getter: - (id)video;
- (void)willHide;
- (void)willShowAlert;
- (void)willShowForVideo:(id)video inList:(id)list orVideoID:(id)anId;
@end

