/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YTNetworkController.h"
#import <Foundation/Foundation.h>
#import "YouTube-Structs.h"

@interface YTNetworkController : NSObject {
	SCDynamicStoreRef _store;
	NSTimer *_notificationTimer;
	int _networkType;
}
@property(readonly, assign) int networkType;	// converted property
+ (id)sharedNetworkController;
// converted property getter: - (int)networkType;
- (void)start;
@end

@interface YTNetworkController (Internal)
- (void)_checkForNetwork;
- (void)_checkForNetworkAndNotify;
- (void)_scheduleCheckForNetwork;
@end

