/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YTVideoDataSource.h"
#import "YTVideo.h"

@interface YTRelatedVideoDataSource : YTVideoDataSource {
	YTVideo *_video;
}
- (void)dealloc;
- (void)reloadData;
- (void)setVideo:(id)video;
@end

