/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>
#import "YTVideoDataSource.h"

@interface YTSearchVideoDataSource : YTVideoDataSource {
	NSString *_searchString;
}
@property(retain) NSString *searchString;	// converted property
- (id)init;
- (void)reloadData;
// converted property getter: - (id)searchString;
// converted property setter: - (void)setSearchString:(id)string;
@end

