/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YTFeedRequest.h"

@interface YTSearchRequest : YTFeedRequest {
}
+ (id)feedCountryCode;
+ (unsigned)videosPerRequest;
- (void)didParseData;
- (void)failWithError:(id)error;
- (BOOL)receivedValidResponse:(id)response;
- (void)searchForFavoriteVideosStartingAtIndex:(unsigned)index withDelegate:(id)delegate;
- (void)searchForMyVideosStartingAtIndex:(unsigned)index withDelegate:(id)delegate;
- (void)searchForRecentVideosStartingAtIndex:(unsigned)index withDelegate:(id)delegate;
- (void)searchForVideoWithID:(id)anId withDelegate:(id)delegate;
- (void)searchForVideosByAuthor:(id)videosByAuthor startingAtIndex:(unsigned)index maxResults:(unsigned)results withDelegate:(id)delegate;
- (void)searchForVideosMatchingString:(id)videosMatchingString startingAtIndex:(unsigned)index withDelegate:(id)delegate;
- (void)searchForVideosRelatedToVideo:(id)video startingAtIndex:(unsigned)index maxResults:(unsigned)results withDelegate:(id)delegate;
- (void)searchForVideosWithFeedURLBase:(id)feedURLBase startingAtIndex:(unsigned)index maxResults:(int)results withTimeQualifier:(id)timeQualifier authenticationRequired:(BOOL)required withDelegate:(id)delegate;
- (void)searchForVideosWithIDs:(id)ids withDelegate:(id)delegate;
@end

