/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>
#import "YouTube-Structs.h"
#import "XMLSAXHTTPRequest.h"

@interface YTSubscriptionsRequest : XMLSAXHTTPRequest {
	id _delegate;
	NSMutableArray *_subscriptions;
	int _mode;
	NSMutableURLRequest *_deferredRequest;
}
+ (id)URLForSubscription:(id)subscription;
+ (id)displayStringForSubscription:(id)subscription;
+ (BOOL)isSubscription:(id)subscription channelOfUser:(id)user;
- (id)init;
- (void)_didAuthenticate:(id)authenticate;
- (void)_doRequestWithURL:(id)url;
- (void)_failedToAuthenticate:(id)authenticate;
- (void)_listenForAuthenticationNotifications:(BOOL)authenticationNotifications;
- (void)createPlaylistNamed:(id)named;
- (void)dealloc;
- (void)didParseData;
- (void)failWithError:(id)error;
- (void)loadRequest:(id)request;
- (int)parseData:(id)data;
- (void)requestPlaylists;
- (void)requestSubscriptions;
- (void)setDelegate:(id)delegate;
@end

