/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>
#import "YTVideoDataSource.h"

@interface YTTimeQualifiedVideoDataSource : YTVideoDataSource {
	NSString *_timeQualifier;
}
- (void)setTimeQualifier:(id)qualifier clearVideos:(BOOL)videos;
@end

