/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import "YouTube-Structs.h"
#import <Foundation/Foundation.h>

@class NSCalendarDate;

@interface YTVideo : NSObject {
	NSString *_id;
	NSString *_title;
	NSString *_author;
	NSCalendarDate *_dateUpdated;
	NSCalendarDate *_dateAdded;
	NSArray *_videoReferences;
	NSString *_notificationName;
	NSString *_videoDescription;
	NSString *_category;
	NSArray *_tags;
	unsigned _numberOfViews;
	unsigned _numberOfRatings;
	unsigned _minRating;
	unsigned _maxRating;
	unsigned _rating;
	int _batchStatus;
	NSURL *_infoURL;
	NSURL *_thumbnailURL;
	NSURL *_commentsURL;
	NSURL *_editURL;
	NSURL *_ratingsURL;
	NSString *_shortID;
	NSString *_unplayable;
	BOOL _isProcessing;
}
@property(readonly, retain) NSString *author;	// converted property
@property(readonly, assign) int batchStatus;	// converted property
@property(readonly, retain) NSString *category;	// converted property
@property(readonly, retain) NSURL *commentsURL;	// converted property
@property(readonly, retain) NSCalendarDate *dateAdded;	// converted property
@property(readonly, retain) NSCalendarDate *dateUpdated;	// converted property
@property(readonly, retain) NSURL *editURL;	// converted property
@property(readonly, retain) NSURL *infoURL;	// converted property
@property(readonly, assign) BOOL isProcessing;	// converted property
@property(readonly, assign) unsigned maxRating;	// converted property
@property(readonly, assign) unsigned minRating;	// converted property
@property(readonly, assign) unsigned numberOfRatings;	// converted property
@property(readonly, assign) unsigned numberOfViews;	// converted property
@property(readonly, assign) unsigned rating;	// converted property
@property(readonly, retain) NSURL *ratingsURL;	// converted property
@property(readonly, retain) NSString *shortID;	// converted property
@property(readonly, retain) NSArray *tags;	// converted property
@property(readonly, retain) NSURL *thumbnailURL;	// converted property
@property(readonly, retain) NSString *title;	// converted property
@property(readonly, retain) NSString *unplayable;	// converted property
@property(readonly, retain) NSString *videoDescription;	// converted property
+ (void)disableNotifications;
+ (void)enableNotifications;
+ (void)playbackDidStall;
+ (void)reset3GPlaybackStallCount;
+ (NSError *)unsupportedVideoError;
+ (NSError *)videoIsProcessingError;
+ (NSError *)videoNotFoundError;
- (id)initFromArchiveDictionary:(id)archiveDictionary;
- (id)initWithID:(id)anId title:(id)title dateUpdated:(id)updated dateAdded:(id)added videoReferences:(id)references infoURL:(id)url videoDescription:(id)description category:(id)category tags:(id)tags author:(id)author thumbnailURL:(id)url11 minRating:(unsigned)rating maxRating:(unsigned)rating13 rating:(unsigned)rating14 numberOfRatings:(unsigned)ratings numberOfViews:(unsigned)views batchStatus:(int)status commentsURL:(id)url18 editURL:(id)url19 ratingsURL:(id)url20 shortID:(id)anId21 unplayable:(id)unplayable isProcessing:(BOOL)processing;
- (NSString *)ID;
- (void)_postVideoDidChange;
- (void)_thumbnailDidLoad;
- (double)age;
- (id)anyVideoReference;
- (NSDictionary *)archiveDictionary;
// converted property getter: - (id)author;
// converted property getter: - (int)batchStatus;
- (id)bestVideoReference;
// converted property getter: - (id)category;
// converted property getter: - (id)commentsURL;
// converted property getter: - (id)dateAdded;
- (NSString *)dateAddedString;
// converted property getter: - (id)dateUpdated;
- (void)dealloc;
// converted property getter: - (id)editURL;
- (unsigned)hash;
// converted property getter: - (id)infoURL;
- (BOOL)isBookmarked;
- (BOOL)isEqual:(id)equal;
- (BOOL)isPlayable;
// converted property getter: - (BOOL)isProcessing;
- (CGImageRef)largeThumbnailLoadIfAbsent:(BOOL)absent;
// converted property getter: - (unsigned)maxRating;
// converted property getter: - (unsigned)minRating;
// converted property getter: - (unsigned)numberOfRatings;
// converted property getter: - (unsigned)numberOfViews;
- (CGImageRef)pluginThumbnailLoadIfAbsent:(BOOL)absent;
// converted property getter: - (unsigned)rating;
// converted property getter: - (id)ratingsURL;
- (CGImageRef)roundedThumbnailLoadIfAbsent:(BOOL)absent;
// converted property getter: - (id)shortID;
// converted property getter: - (id)tags;
- (NSString *)tagsString;
- (CGImageRef)thumbnailLoadIfAbsent:(BOOL)absent;
// converted property getter: - (id)thumbnailURL;
// converted property getter: - (id)title;
// converted property getter: - (id)unplayable;
// converted property getter: - (id)videoDescription;
- (id)videoReferenceForProfile:(int)profile;
@end

