/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/YouTube.framework/YouTube
 */

#import <Foundation/Foundation.h>

@interface YTVideoReference : NSObject {
	NSURL *_contentURL;
	unsigned _duration;
	int _profile;
}
@property(readonly, retain) NSURL *contentURL;	// converted property
@property(readonly, assign) unsigned duration;	// converted property
@property(readonly, assign) int profile;	// converted property
- (id)initFromArchiveDictionary:(id)archiveDictionary;
- (id)initWithContentURL:(NSURL *)contentURL duration:(unsigned)duration profile:(int)profile;
- (NSDictionary *)archiveDictionary;
// converted property getter: - (id)contentURL;
- (void)dealloc;
// converted property getter: - (unsigned)duration;
// converted property getter: - (int)profile;
@end

